# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
    - job: FirstJob
      steps:
      - bash: echo build first job 
    - job: Second
      steps:
      - bash: echo build second job       
  - stage: devdeploy
    jobs:
    - job: devdeploy
      steps:
      - bash: echo deploy dev 
  - stage: qadeploy
    jobs:
    - job: qadeploy
      steps:
      - bash: echo deploy qa 
  - stage: prddeploy
    jobs:
    - job: prddeploy
      steps:
      - bash: echo deploy prd