# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      job: FirstJob
      steps:
      - echo build firts job 
  - stage: devdeploy
    jobs:
      job: devdeploy
      steps:
      - echo deploy dev 
  - stage: qadeploy
    jobs:
      job: qadeploy
      steps:
      - echo deploy qa 
  - stage: prddeploy
    jobs:
      job: prddeploy
      steps:
      - echo deploy prd

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
