# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Pipelines >> stages >> jobs >> tags or steps
jobs:
- job: Job01 
  steps:
  - script: echo Job01 Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job02
  dependsOn: Job01
  steps:
  - script: echo Job02 - Hello, world!
    displayName: 'Run a one-line script'
- job: Job03
  dependsOn: Job02
  steps:
  - script: echo Job03 - Hello, world!
    displayName: 'Run a one-line script'
- job: Job04
  dependsOn: 
  - Job02
  - Job03
  steps:
  - script: echo Job03 - Hello, world!
    displayName: 'Run a one-line script'    